[book]
authors = ["msaug", "julio4"]
language = "en"
multilingual = false
src = "src"
title = "Starknet by Example"

[build]
extra-watch-dirs = ["listings", "po"]

[preprocessor.gettext]
after = ["links"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/NethermindEth/StarknetByExample"
edit-url-template = "https://github.com/NethermindEth/StarknetByExample/edit/main/{path}"
playground.runnable = false
fold.enable = true
fold.level = 2
additional-css = ["theme/css/last-changed.css"]
