[package]
name = "timelock"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_utils.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
components.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
