[package]
name = "simple_storage"
version.workspace = true
edition = "2024_07"

[lib]

[dependencies]
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true
 
[[target.starknet-contract]]