[package]
name = "upgradeable_contract"
version.workspace = true
edition = "2024_07"

[dependencies]
starknet.workspace = true

[dev-dependencies]
cairo_test.workspace = true
 
[[target.starknet-contract]]
