[package]
name = "crowdfunding"
version.workspace = true
edition = "2023_11"

[lib]

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
components.workspace = true
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
casm = true
