[package]
name = "mappings"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
cairo_test = "2.7.1"

[scripts]
test.workspace = true

[[target.starknet-contract]]
