[package]
name = "constant_product_amm"
version.workspace = true
edition = '2023_10'

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
