name: Verify Cairo programs compilation

on:
  pull_request:
    branches:
      - main

jobs:
  compile_and_verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure upstream repository
        run: |
          git remote add upstream https://github.com/NethermindEth/StarknetByExample
          git fetch upstream main

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1

      - name: Run build script
        run: |
          chmod +x scripts/cairo_programs_verifier.sh
          ./scripts/cairo_programs_verifier.sh
