[package]
name = "components_dependencies"
version.workspace = true
edition = '2023_10'

[dependencies]
starknet.workspace = true
components = { path = "../components" }

[scripts]
test.workspace = true

[[target.starknet-contract]]
