[package]
name = "components_dependencies"
version.workspace = true
edition = "2024_07"

[dependencies]
starknet.workspace = true
components = { path = "../components" }

[dev-dependencies]
cairo_test.workspace = true
 
[[target.starknet-contract]]
